### ISSUE TITLE
Donation Address is missed

### ISSUE THREAD

**Issue by b00f** [frimin/pactus-staker#1]
This is an amazing job, @frimin, and it will help many users automatically send bond transactions to their validators. I believe this project will be recognized by the community, and they may want to donate some PAC as a token of appreciation. From what I can see in the README, the donation address is missing. It would be good to add one.

**Comment by frimin** [comment]
I have added the donation address to the README, hoping for a miracle. 👻

**Comment by b00f** [comment]
Miracles come from your work and dedication to the good of the community. That is important. Having this mindset helps improve our daily lives.
